# Generated by Django 5.0.1 on 2024-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_facerecognition_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecognition',
            name='age',
        ),
        migrations.RemoveField(
            model_name='facerecognition',
            name='gender',
        ),
        migrations.AddField(
            model_name='facerecognition',
            name='image',
            field=models.TextField(default='none'),
        ),
    ]
