# Generated by Django 5.0.1 on 2024-01-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_remove_facerecognition_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaceRecognition',
            new_name='KnownFace',
        ),
    ]
