# Generated by Django 5.0.1 on 2024-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognition',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2004-06-20 11:59'),
            preserve_default=False,
        ),
    ]
