# Generated by Django 5.0.1 on 2024-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='forgot_pass_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_num',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
